Revision/edit listado grupos
ccsw-csd/teammanager-client pull request #2
Opened 2023-03-28 06:32 UTC by pauanran

Revision de edit-list-group porque devuelve data data vacio

2023-03-29 14:06 UTC, pauanran commented
Finalizado la edicion de listado  de  grupos.

2023-03-29 14:43 UTC, pajimene requested changes
Revisa los cambios

2023-03-29 14:43 UTC, pajimene commented on package.json
> +    "@angular/material": "~13.2.0",
No estamos usando material, bórralo de las dependencias

2023-03-29 14:43 UTC, pajimene commented on package.json
> +    "angular-material": "^1.2.5",
No estamos usando material, bórralo de las dependencias

2023-03-29 14:43 UTC, pajimene commented on package.json
> +    "axios": "^1.3.4",
No estamos usando axios, bórralo de las dependencias

2023-03-29 14:43 UTC, pajimene commented on package.json
> +  "description": "This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 11.0.5.",
Todo este bloque es añadido a las dependencias, sobra

2023-03-29 14:43 UTC, pajimene commented on src/app/group/group.module.ts
> +import { MAT_DIALOG_DATA, MatDialogModule } from '@angular/material/dialog';
No estamos usando material, bórralo de las dependencias

2023-03-29 14:43 UTC, pajimene commented on src/app/group/group.module.ts
> +    MatDialogModule,
No estamos usando material, bórralo de las dependencias

2023-03-29 14:43 UTC, pajimene commented on src/app/group/group.module.ts
> +    {
No estamos usando material, borra el provider de material

2023-03-29 14:43 UTC, pajimene commented on src/app/group/models/GroupPage.ts
> +export class GroupPage {
GroupPage no se utiliza en ningún sitio, lo puedes borrar

2023-03-29 14:43 UTC, pajimene commented on src/app/group/services/group.service.ts
> +  getSubgroups(name: string): Observable<Group[]> {
Este método sobra, no hay que llamar a subgrupos

2023-03-29 14:43 UTC, pajimene commented on src/app/group/services/group.service.ts
> +  getPersons(name: string): Observable<Person[]> {
Este método sobra, no hay que llamar a personas

2023-03-29 14:43 UTC, pajimene commented on src/app/group/views/group-edit/group-edit.component.html
> +        <p-inputSwitch></p-inputSwitch>
Le falta un texto a este switch que diga "Visible for members"

2023-03-29 14:43 UTC, pajimene commented on src/app/group/views/group-edit/group-edit.component.html
> +    <div class="text-black-alpha-50 mt-3">
No lo separes en dos divs, usa los Float Label (https://primeng.org/inputtext#floatlabel)

2023-03-29 14:43 UTC, pajimene commented on src/app/group/views/group-edit/group-edit.component.html
> +      <button pButton pRipple label="Close" icon="pi pi-times" class="bg-white text-blue-400 w-12rem m-2 mt-0" (click)="onClose()"></button>
No le pongas iconos a los botones

2023-03-29 14:43 UTC, pajimene commented on src/app/group/views/group-edit/group-edit.component.html
> +<div class="flex flex-column">
Sale scroll en la ventana, no debería, si hace falta scroll debe salir solo dentro de los listados

2023-03-29 14:43 UTC, pajimene commented on src/app/group/views/group-edit/group-edit.component.scss
> +::ng-deep{
Nada de estilos, lo que venga por defecto, no tiene que ser exacto a la imagen de la tarea

2023-03-29 14:43 UTC, pajimene commented on src/app/group/views/group-edit/group-edit.component.ts
> +  subgroup: Group;
Todas las siguientes propiedades no te hacen falta, SOLO necesitas el group de ahí se saca toda la info

2023-03-29 14:43 UTC, pajimene commented on src/app/group/views/group-edit/group-edit.component.ts
> +      this.getSubgroups(this.group.name);
Estas tres llamadas no te hacen falta, la info la tienes en group.

group.managers
group.members
group.subgroups

2023-03-29 14:43 UTC, pajimene commented on src/app/group/views/group-list/group-list.component.scss
> +@import "./src/assets/scss/master";
Fuera todos los estilos

2023-03-29 14:43 UTC, pajimene commented on src/app/group/views/group-list/group-list.component.html
> +        <p-inputSwitch [(ngModel)]="adminView"
Le falta un texto al inputSwitch que diga "Admin View"

2023-03-29 14:43 UTC, pajimene commented on src/app/group/views/group-list/group-list.component.ts
> +      this.adminView = true;
Nunca lo seteas a false?

2023-03-31 09:29 UTC, pajimene approved these changes

2023-03-31 09:34 UTC, merged